name = "Wolke"
license = "MIT"
licenselink = "https://github.com/39e/hugo-wolke/blob/master/LICENSE.md"
description = "Grid based theme for Hugo."
homepage = "https://github.com/39e/hugo-wolke"
tags = ["blog"]
features = ["responsive", "thumbnail", "grid", "structured data", "ogp", "twitter cards"]
min_version = 0.42

[author]
name = "Aoi Tachibana"
homepage = "https://ress.arukas.xyz"
